#!/bin/bash

read -p "ENTER YOUR FILE LOCATION : " $location

echo " THE SIZE OF EACH FILE IS : "
ls -l $location | awk -F" " '{print $5}'


OUTPUT:

kajal@DESKTOP-FFMPO9M MINGW64 ~/Desktop/BashCommands (master)
$ bash Task.sh
ENTER YOUR FILE LOCATION : desktop
 THE SIZE OF EACH FILE IS :

0
0
0
362
37
37
349
256
240
0
28
362
116
141
79
475
116
68
141
61197
0
0
0
0
0



